---
# tasks file for web

  - name: Install Nginx
    apt: name=nginx state=latest

  - name: Install Apache
    apt: name=apache2 state=latest

  - name: Install PHP
    apt: name={{ item }} state=latest
    with_items:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip

  - name: Install  bind9
    apt: name=bind9 state=latest

  - name: Download zabbix repo package
    get_url:
        url: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu20.04_all.deb
        dest: /tmp/zabbix.deb

  - name: dpkg zabbix
    dpkg_selections: name=zabbix.deb  selection=hold

  - name: Install zabbix agent
    apt: name=zabbix-agent state=present  update_cache=yes

  - name:  Install mail
    apt: name={{ item }} state=latest
    with_items:
      - postfix
      - dovecot-core
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-lmtpd
      - mysql-server
      - roundcube

  - name: Download zabbix repo package
    get_url:
        url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.1-amd64.deb
        dest: /tmp/filebeat.deb

  - name: Install filebeat
    apt:
      deb: /tmp/filebeat.deb
